schema_version: 1

context:
  version: "1.5.0"

package:
  name: trame-dataclass
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/trame-dataclass/trame_dataclass-${{ version }}.tar.gz
  sha256: bd679a25ccf8aa4593d740d418ffd5d37b0d845e4276b72df281f44be4c7ec74

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - trame-client >=3.10
    - loguru

tests:
  - python:
      imports:
        - trame_dataclass
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Dataclass for trame UI binding
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://pypi.org/project/trame-dataclass/

extra:
  recipe-maintainers:
    - jourdain
    - psavery
    - alesgenova
